# Generate lib/tones-data.js: every built-in tone as one base64 string, so the
# client bundle carries them inline and needs no sibling file at runtime.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed-tones.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed-tones.ps1 -Check
#
# The tone list is fixed: adding a tone means adding its asset here and its entry
# in lib/client.js (TONE_LIBRARY). -Check fails when the generated module and the
# assets disagree, which is what CI runs.
[CmdletBinding()]
param(
  [string]$AssetsDir,
  [string]$OutputPath,
  [switch]$Check
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
if (-not $AssetsDir) { $AssetsDir = Join-Path $root 'assets' }
if (-not $OutputPath) { $OutputPath = Join-Path $root 'lib\tones-data.js' }

# id -> asset file name. Order is the order the settings list shows.
$tones = [ordered]@{
  'bingbingbing' = 'bingbingbing.ogg'
  'crisp-a'      = 'crisp-a.ogg'
  'crisp-b'      = 'crisp-b.ogg'
}

$entries = @()
foreach ($id in $tones.Keys) {
  $file = Join-Path $AssetsDir $tones[$id]
  if (-not (Test-Path $file)) { throw "tone asset not found: $file" }
  $bytes = [System.IO.File]::ReadAllBytes($file)
  if ($bytes.Length -lt 500) { throw "tone asset looks too small: $file ($($bytes.Length) bytes)" }
  $magic = [System.Text.Encoding]::ASCII.GetString($bytes[0..3])
  if ($magic -ne 'OggS') { throw "$file is not an Ogg stream (magic '$magic')" }
  $entries += [pscustomobject]@{
    id      = $id
    source  = $tones[$id]
    bytes   = $bytes.Length
    base64  = [Convert]::ToBase64String($bytes)
  }
}

# ---- generated module --------------------------------------------------------

$lines = @()
$lines += '// Generated by tools/embed-tones.ps1 - do not edit by hand.'
$lines += '//'
$lines += '// Every built-in tone the settings page offers, as base64 Ogg Vorbis. The'
$lines += '// payloads are inline so the client bundle resolves nothing but `react` at'
$lines += '// runtime. Regenerate after adding or replacing an asset:'
$lines += '//   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed-tones.ps1'
$lines += ''
$lines += '/** Tone id -> the asset file it was generated from (informational). */'
$lines += 'export const TONE_SOURCES = {'
foreach ($entry in $entries) { $lines += "  '$($entry.id)': '$($entry.source)'," }
$lines += '};'
$lines += ''
$lines += '/** Tone id -> base64 of its Ogg Vorbis payload. */'
$lines += 'export const TONE_BASE64 = {'
foreach ($entry in $entries) {
  $lines += "  '$($entry.id)':"
  $chunks = @()
  for ($i = 0; $i -lt $entry.base64.Length; $i += 96) {
    $length = [Math]::Min(96, $entry.base64.Length - $i)
    $chunks += "    '" + $entry.base64.Substring($i, $length) + "'"
  }
  # One concatenated string per tone: every chunk but the last gets a `+`, and the
  # entry is terminated with a comma on the last chunk.
  for ($c = 0; $c -lt $chunks.Count; $c++) {
    if ($c -lt $chunks.Count - 1) { $lines += ($chunks[$c] + ' +') }
    else { $lines += ($chunks[$c] + ',') }
  }
}
$lines += '};'
$generated = ($lines -join "`n") + "`n"

$utf8 = New-Object System.Text.UTF8Encoding($false)

if ($Check) {
  if (-not (Test-Path $OutputPath)) { throw "generated module not found: $OutputPath (run tools\embed-tones.ps1)" }
  $current = [System.IO.File]::ReadAllText($OutputPath, $utf8)
  $missing = @()
  foreach ($entry in $entries) {
    # The module wraps each payload into 96-char chunks, so compare on a fixed
    # slice length that cannot straddle a wrap.
    if (-not $current.Contains($entry.base64.Substring(0, 90))) { $missing += $entry.id }
  }
  if ($missing.Count -gt 0) {
    throw "lib/tones-data.js is out of date for: $($missing -join ', ') - run tools\embed-tones.ps1"
  }
  Write-Host "tones-data.js matches assets: $($entries.Count) tones"
  return
}

[System.IO.File]::WriteAllText($OutputPath, $generated, $utf8)
foreach ($entry in $entries) {
  Write-Host ("  {0,-14} {1,8} bytes -> {2,8} base64 chars" -f $entry.id, $entry.bytes, $entry.base64.Length)
}
Write-Host "wrote $OutputPath"
